# configuration for https://github.com/repository-settings/app
# - warning: branch protection cannot be configured here - see https://github.com/repository-settings/app/issues/150

# Permissions documentation snippet:
# * `pull` - can pull, but not push to or administer this repository.
# * `push` - can pull and push, but not administer this repository.
# * `admin` - can pull, push and administer this repository.
# * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
# * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.

repository:
  name: catalog
  description: Repository with Custom Resource Definition files for validation purposes
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

collaborators:
  - username: CodeReaper
    permission: admin
  - username: Karl-koder
    permission: admin
  - username: ole-kaas
    permission: admin

teams:
  # Please make sure the team already exist in the organization, as the repository-settings application is not creating them.
  # See https://github.com/repository-settings/app/discussions/639 for more information about teams and settings
  - name: sources-maintainers
    permission: push
  - name: core-maintainers
    permission: push
  - name: github-administrators
    permission: maintain
