- entries:
    - connect
  kind: helm
  name: 1password
  repository: https://1password.github.io/connect-helm-charts
- entries:
    - aad-pod-identity
  kind: helm
  name: aad-pod-identity
  repository: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
- entries:
    - actions-runner-controller
  kind: helm
  name: actions-runner-controller
  repository: https://actions-runner-controller.github.io/actions-runner-controller
- additionalVersions:
    - 1.0.12
  kind: helm-oci
  name: apigatewayv2-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart
- entries:
    - apisix-ingress-controller
  kind: helm
  name: apisix
  repository: https://charts.apiseven.com
- additionalVersions:
    - 1.0.14
  kind: helm-oci
  name: applicationautoscaling-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/applicationautoscaling-chart
- entries:
    - argo-cd
    - argo-events
    - argo-rollouts
    - argo-workflows
  kind: helm
  name: argo
  repository: https://argoproj.github.io/argo-helm
- entries:
    - awx-operator
  kind: helm
  name: awx-operator
  repository: https://ansible.github.io/awx-operator
- entries:
    - volsync
  kind: helm
  name: backube
  repository: https://backube.github.io/helm-charts
- entries:
    - vault-operator
  kind: helm
  name: banzaicloud-stable
  repository: https://kubernetes-charts.banzaicloud.com
- entries:
    - contour
    - flux
    - rabbitmq-cluster-operator
    - sealed-secrets
  kind: helm
  name: bitnami
  repository: https://charts.bitnami.com/bitnami
- entries:
    - cert-manager
  kind: helm
  name: cert-manager
  repository: https://charts.jetstack.io
  valuesFile: |
    installCRDs: true
- entries:
    - trust-manager
  kind: helm
  name: cert-trust-manager
  repository: https://charts.jetstack.io
- kind: git
  name: cilium
  repository: https://github.com/cilium/cilium
  searchPaths:
    - pkg/k8s/apis/cilium.io/client/crds
  versionPrefix: v
- entries:
    - altinity-clickhouse-operator
  kind: helm
  name: clickhouse-operator
  repository: https://docs.altinity.com/clickhouse-operator/
- entries:
    - cloudnative-pg
  kind: helm
  name: cloudnative-pg
  repository: https://cloudnative-pg.github.io/charts
- additionalVersions:
    - 1.0.11
  kind: helm-oci
  name: cloudtrail-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/cloudtrail-chart
- additionalVersions:
    - 5.5.2
  kind: helm-oci
  name: crunchydata-pgo
  repository: oci://registry.developers.crunchydata.com/crunchydata/pgo
- entries:
    - dapr
  kind: helm
  name: dapr
  repository: https://dapr.github.io/helm-charts
- entries:
    - datadog-operator
  kind: helm
  name: datadog
  repository: https://helm.datadoghq.com
- entries:
    - druid-operator
  kind: helm
  name: datainfra
  repository: https://charts.datainfra.io
- entries:
    - ambassador
  kind: helm
  name: datawire
  repository: https://getambassador.io
- kind: git
  kustomizationPaths:
    - config/crd
  name: dbaas-operator
  repository: https://github.com/percona/dbaas-operator
  versionPrefix: v
- entries:
    - doppler-kubernetes-operator
  kind: helm
  name: doppler
  repository: https://helm.doppler.com
- additionalVersions:
    - 1.2.11
  kind: helm-oci
  name: dynamodb-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/dynamodb-chart
- kind: git
  kustomizationPaths:
    - config/crd
  name: dynatrace-operator
  repository: https://github.com/Dynatrace/dynatrace-operator
  versionPrefix: v
- additionalVersions:
    - 1.2.9
  kind: helm-oci
  name: ec2-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/ec2-chart
- additionalVersions:
    - 1.0.15
  kind: helm-oci
  name: ecr-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/ecr-chart
- kind: git
  kustomizationPaths:
    - config/crd
  name: eks-anywhere
  repository: https://github.com/aws/eks-anywhere
  versionPrefix: v
- additionalVersions:
    - 1.3.5
  kind: helm-oci
  name: eks-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/eks-chart
- entries:
    - eck-operator
    - eck-operator-crds
  kind: helm
  name: elastic
  repository: https://helm.elastic.co
- entries:
    - emqx-operator
  kind: helm
  name: emqx
  repository: https://repos.emqx.io/charts
- additionalVersions:
    - 1.0.10
  kind: helm-oci
  name: emrcontainers-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/emrcontainers-chart
- additionalVersions:
    - 1.0.11
  kind: helm-oci
  name: eventbridge-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/eventbridge-chart
- entries:
    - external-secrets
  kind: helm
  name: external-secrets-operator
  repository: https://charts.external-secrets.io
- entries:
    - rbac-manager
  kind: helm
  name: fairwinds-stable
  repository: https://charts.fairwinds.com/stable
- entries:
    - flagger
  kind: helm
  name: flagger
  repository: https://flagger.app
- entries:
    - flink-kubernetes-operator
  kind: helm
  name: flink-operator-repo
  repository: https://downloads.apache.org/flink/flink-kubernetes-operator-1.8.0
- entries:
    - gatekeeper
  kind: helm
  name: gatekeeper
  repository: https://open-policy-agent.github.io/gatekeeper/charts
- additionalVersions:
    - 0.9.2
  kind: helm-oci
  name: gha-runner-scale-set-controller
  repository: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
- entries:
    - gitlab-operator
  kind: helm
  name: gitlab
  repository: https://charts.gitlab.io
- entries:
    - gloo
  kind: helm
  name: gloo
  repository: https://storage.googleapis.com/solo-public-helm
- entries:
    - alloy
    - grafana-agent
    - grafana-agent-operator
    - k6-operator
    - k8s-monitoring
  kind: helm
  name: grafana
  repository: https://grafana.github.io/helm-charts
  valuesFile: |
    cluster:
      name: my-cluster

    externalServices:
      prometheus:
        host: https://prometheus.example.com
        basicAuth:
          username: "12345"
          password: "It's a secret to everyone"
      loki:
        host: https://loki.example.com
        basicAuth:
          username: "67890"
          password: "It's a secret to everyone"
- entries:
    - vault-secrets-operator
  kind: helm
  name: hashicorp
  repository: https://helm.releases.hashicorp.com
- additionalVersions:
    - 1.3.8
  kind: helm-oci
  name: iam-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/iam-chart
- entries:
    - base
  kind: helm
  name: istio
  repository: https://istio-release.storage.googleapis.com/charts
- entries:
    - jaeger-operator
  kind: helm
  name: jaegertracing
  repository: https://jaegertracing.github.io/helm-charts
- entries:
    - karpenter
  kind: helm
  name: karpenter
  repository: https://charts.karpenter.sh
- entries:
    - keda
  kind: helm
  name: kedacore
  repository: https://kedacore.github.io/charts
- additionalVersions:
    - 1.0.13
  kind: helm-oci
  name: kms-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/kms-chart
- entries:
    - ingress
    - kong
  kind: helm
  name: kong
  repository: https://charts.konghq.com
- kind: git
  kustomizationPaths:
    - manifests/base/crds
  name: kubeflow-training-operator
  repository: https://github.com/kubeflow/training-operator
  versionPrefix: v
- kind: git
  kustomizationPaths:
    - config/crd
  name: kubernetes-sigs-cluster-api
  repository: https://github.com/kubernetes-sigs/cluster-api
  versionPrefix: v
- entries:
    - kyverno
  kind: helm
  name: kyverno
  repository: https://kyverno.github.io/kyverno
- additionalVersions:
    - 1.5.0
  kind: helm-oci
  name: lambda-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/lambda-chart
- additionalVersions:
    - 1.0.2
  kind: helm-oci
  name: memorydb-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/memorydb-chart
- entries:
    - metallb
  kind: helm
  name: metallb
  repository: https://metallb.github.io/metallb
- entries:
    - minio-operator
  kind: helm
  name: minio-operator
  repository: https://operator.min.io
- entries:
    - community-operator-crds
    - enterprise-operator
    - mongodb-atlas-operator-crds
  kind: helm
  name: mongodb
  repository: https://mongodb.github.io/helm-charts
- kind: git
  name: multus-cni
  repository: https://github.com/k8snetworkplumbingwg/multus-cni
  searchPaths:
    - deployments
  versionPrefix: v
- entries:
    - mysql-operator
  kind: helm
  name: mysql-operator
  repository: https://mysql.github.io/mysql-operator
- additionalVersions:
    - 1.2.2
  kind: helm-oci
  name: nginx-ingress
  repository: oci://ghcr.io/nginxinc/charts/nginx-ingress
- kind: git
  name: oci-native-ingress-controller
  repository: https://github.com/oracle/oci-native-ingress-controller
  searchPaths:
    - helm/oci-native-ingress-controller/crds
  versionPrefix: v
- entries:
    - openebs
  kind: helm
  name: openebs
  repository: https://openebs.github.io/openebs
- kind: git
  kustomizationPaths:
    - config/crd
  name: openshift-cluster-logging-operator
  repository: https://github.com/openshift/cluster-logging-operator
  versionPrefix: unversioned
  includeHead: true
- entries:
    - opentelemetry-operator
  kind: helm
  name: opentelemetry-helm
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  valuesFile: |
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-k8s
- additionalVersions:
    - 1.0.8
  kind: helm-oci
  name: pipes-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/pipes-chart
- entries:
    - postgres-operator
  kind: helm
  name: postgres-operator-charts
  repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
- entries:
    - tigera-operator
  kind: helm
  name: projectcalico
  repository: https://docs.projectcalico.org/charts
- entries:
    - kube-prometheus-stack
  kind: helm
  name: prometheus-community
  repository: https://prometheus-community.github.io/helm-charts
- additionalVersions:
    - 1.2.11
  kind: helm-oci
  name: prometheusservice-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/prometheusservice-chart
- additionalVersions:
    - 1.2.5
  kind: helm-oci
  name: rds-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/rds-chart
- additionalVersions:
    - 1.0.12
  kind: helm-oci
  name: s3-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/s3-chart
- additionalVersions:
    - 1.2.11
  kind: helm-oci
  name: sagemaker-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/sagemaker-chart
- entries:
    - scylla-operator
  kind: helm
  name: scylla-operator
  repository: https://storage.googleapis.com/scylla-operator-charts/stable
- additionalVersions:
    - 1.0.11
  kind: helm-oci
  name: sfn-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/sfn-chart
- entries:
    - sloth
  kind: helm
  name: sloth
  repository: https://slok.github.io/sloth
- additionalVersions:
    - 1.0.11
  kind: helm-oci
  name: sns-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/sns-chart
- entries:
    - spark-operator
  kind: helm
  name: spark-operator
  repository: https://kubeflow.github.io/spark-operator
- apiGroups:
    - databases.spotahome.com
  crds:
    - baseUri: https://raw.githubusercontent.com/spotahome/redis-operator/v1.2.4/charts/redisoperator/crds
      paths:
        - databases.spotahome.com_redisfailovers.yaml
      version: 1.12.0
  kind: http
  name: spotahome_redis-operator
- entries:
    - akv2k8s
  kind: helm
  name: spv-charts
  repository: https://charts.spvapi.no
- additionalVersions:
    - 1.0.13
  kind: helm-oci
  name: sqs-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s/sqs-chart
- entries:
    - strimzi-kafka-operator
  kind: helm
  name: strimzi
  repository: https://strimzi.io/charts
- entries:
    - teleport-operator
  kind: helm
  name: teleport-agent-kube
  repository: https://charts.releases.teleport.dev
  valuesFile: |
    chartMode: standalone
    clusterName: teleport.example.com
    teleportAddress: teleport.example.com:443
    teleportClusterName: teleport
- entries:
    - temporal-operator
  kind: helm
  name: temporal-operator
  repository: https://alexandrevilain.github.io/temporal-operator
- entries:
    - tf-controller
  kind: helm
  name: tf-controller
  repository: https://flux-iac.github.io/tofu-controller
- additionalVersions:
    - 0.4.4
  kind: helm-oci
  name: tinkerbell
  repository: oci://ghcr.io/tinkerbell/charts/stack
  valuesFile: |
    smee:
      publicIP: 127.0.0.1
      trustedProxies: localhost
    hegel:
      trustedProxies: localhost
    stack:
      loadBalancerIP: 127.0.0.1
- entries:
    - traefik
  kind: helm
  name: traefik
  repository: https://traefik.github.io/charts
- entries:
    - vault-config-operator
  kind: helm
  name: vault-config-operator
  repository: https://redhat-cop.github.io/vault-config-operator
- entries:
    - victoria-metrics-operator
  kind: helm
  name: vm
  repository: https://victoriametrics.github.io/helm-charts
- entries:
    - velero
  kind: helm
  name: vmware-tanzu
  repository: https://vmware-tanzu.github.io/helm-charts
