name: Scheduled Jobs

on:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  update-schemas:
    name: Update schemas
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: make ci-run
      - uses: EndBug/add-and-commit@v9
        name: Publish changes
        if: github.ref == 'refs/heads/main'
        with:
          add: schema
          default_author: github_actions
