name: Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test

  editorconfig-check:
    name: Editorconfig check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - unit-tests
      - shellcheck
      - editorconfig-check

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
